### ISSUE TITLE
Update composer2

### ISSUE THREAD

**Issue by DanielSiepmann** [fossar/nix-phps#347]
We probably should follow https://github.com/NixOS/nixpkgs/pull/318910 and update composer due to security release: https://blog.packagist.com/composer-2-7-7/

This involves 2.4.x being LTS.

**Comment by drupol** [comment]
Of course. I will trigger a new flake.lock update as soon as I m out of bed and ready to work. Updating this project's flake.lock is the only thing to do actually.

**Comment by DanielSiepmann** [comment]
Thanks :) I'm wondering why there is no need to update https://github.com/fossar/nix-phps/blob/master/pkgs/composer/2.2.nix ? This states 2.2.22, but I'm still not used to flakes.

**Comment by drupol** [comment]
That's the reason: https://github.com/fossar/nix-phps/commit/64fa91cdbafc7ea61e20d064c1fea45a581b63ad

And since there's no update for that old composer branch, using it is risky.

I remember @jtojnar had the idea to write a disclaimer about security and using old versions , maybe we should actually do it.
