### ISSUE TITLE
openssl_1_0_2 is going to be dropped

### ISSUE THREAD

**Issue by jtojnar** [fossar/nix-phps#78]
https://github.com/NixOS/nixpkgs/pull/150880 will drop `openssl_1_0_2`, we need to do something about https://github.com/fossar/nix-phps/blob/4a48a3a771edec188fe648108054cbf22729c08d/pkgs/package-overrides.nix#L207 before then.

**Comment by drupol** [comment]
Hi,

Indeed, we are unable to update to the newest hash. I tried to remove the custom openssl derivation, but it won't build for PHP 5.6, others seems to build fine. The failing tests are not related, mostly because of updated version of Composer.

How should we tackle this issue?

1. Drop support for PHP 5.6?
2. Use a custom version of OpenSSL?

**Comment by jtojnar** [comment]
Trying to backport the openssl update patch (or maybe some other distro has/had it?) would be best option. I would expect the patch to be reasonable clean, though we will probably need to resolve at least a few conflicts.

If that turns to be too much work, I would go with picking up the insecure OpenSSL derivation.

**Comment by drupol** [comment]
I might need help on this. I don't know where or how to start.
